import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Provider from '@/app/_trpc/Provider';
import "./globals.css";
import { TokenProvider } from './_components/login';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Aero",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <TokenProvider>
            {children}
          </TokenProvider>
        </Provider>
      </body>
    </html>
  );
}
